---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: counts
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 2
  configs:
    cleanup.policy: "delete"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordcount
spec:
  serviceName: wordcount
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: wordcount
  template:
    metadata:
      labels:
        app: wordcount
    spec:
      containers:
        - name: datagen-quotes
          image: docker.io/rohit2b/wordcount
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /mnt/app/application.yaml
          volumeMounts:
            - name: spring-boot-word-count-application-yaml
              mountPath: /mnt/app
          resources:
            requests:
              memory: 512Mi # 768Mi
              cpu: 500m # 1000m
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
      volumes:
        - name: spring-boot-word-count-application-yaml
          secret:
            secretName: spring-boot-word-count-application-yaml
---
apiVersion: v1
kind: Service
metadata:
  name: wordcount
spec:
  clusterIP: None
  