apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-word-count-application-yaml
type: Opaque
stringData:
  application.yaml: |
    spring:
      kafka:
        properties:
          bootstrap.servers: kafka.confluent.svc.cluster.local:9071
      cloud:
        stream:
          function:
            definition: processWords
            bindings:
              # input and output of KStreams topology
              processWords-in-0: quotes
              processWords-out-0: counts
          kafka:
            streams:
              binder:
                applicationId: back2future-word-count
                configuration:
                  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
                  commit.interval.ms: 1000 